# Generated by Django 4.2.27 on 2026-01-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MON', 'Monitores'), ('PER', 'Periféricos'), ('HW', 'Hardware')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_serial', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_cambio', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('hora_recibida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('estado_condicion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_anterior', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_actual', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
    ]
